CREATE TABLE User (
	UserID VARCHAR(255) PRIMARY KEY NOT NULL,
	GoogleID VARCHAR(255) NOT NULL UNIQUE,
	RealName VARCHAR(255) NOT NULL UNIQUE,
	EmailAddress VARCHAR(255) NOT NULL UNIQUE,
	BirthDate DATE,
	Course VARCHAR(255),
	AuthProvider VARCHAR(255),
	ProfileImg VARCHAR(255)
);

CREATE TABLE Posts (
	PostID INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
	UserID VARCHAR(255),
	CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
	UpdatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
	Content VARCHAR (1000),
	MediaLink VARCHAR(255),
	FOREIGN KEY (UserID) REFERENCES User(UserID)
);

CREATE TABLE Comments (
	CommentID INT PRIMARY KEY NOT NULL,
	UserID VARCHAR(255),
	PostID INT,
	CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
	UpdatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
	Content VARCHAR (1000),
	FOREIGN KEY (UserID) REFERENCES User(UserID),
	FOREIGN KEY (PostID) REFERENCES Post(PostID)
);

CREATE TABLE Session (
	SessionID VARCHAR(255) PRIMARY KEY NOT NULL,
	RealName VARCHAR(255) NOT NULL,
	Token VARCHAR(255) NOT NULL,
	CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
	UpdatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
	FOREIGN KEY (RealName) REFERENCES User(RealName)
);
