name: Upload a Docker image to AWS ECR

on:
  push:
    branches:
      - pipeline

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Build Docker Image
        run: |
          ls -la
          docker build -t frontend-image -f docker/Dockerfile $GITHUB_WORKSPACE

      - name: Install AWS CLI
        id: install-aws-cli
        uses: unfor19/install-aws-cli-action@v1

      - name: Configure AWS Credentials
        run: |
          mkdir -p ~/.aws/
          echo "$super_secret" > ~/.aws/credentials
        env:
          super_secret: ${{ secrets.AWS_CONFIG }}

      - name: Show AWS Credentials
        run: cat ~/.aws/credentials

      - name: List AWS CLI Profiles
        run: aws configure list-profiles

      - name: List S3 Buckets
        run: aws s3 ls --region eu-central-1 --profile 048479317518_Student

      - name: Amazon ECR Login
        run: aws ecr get-login-password --region eu-central-1 --profile 048479317518_Student | docker login --username AWS --password-stdin 048479317518.dkr.ecr.eu-central-1.amazonaws.com

      - name: Tag Docker Image
        run: docker tag frontend-image ${{ steps.login-ecr.outputs.registry }}:latest

      - name: Push Docker Image to ECR
        run: docker push ${{ steps.login-ecr.outputs.registry }}:latest
