name: Build and Push Docker Image to Dockerhub

on:
  push:
    branches:
      - pipeline

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        run: docker buildx create --use

      - name: Build Docker Image
        id: build-image
        run: |
          ls -la
          docker build -t frontendimage -f docker/Dockerfile $GITHUB_WORKSPACE
          echo "::set-output name=image-name::frontend-image"

      - name: Login to Docker Hub
        run: |
          echo "[$(date -u)] Logging in to Docker Hub..."
          echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
          if [ $? -eq 0 ]; then
            echo "[$(date -u)] Logged in to Docker Hub successfully"
          else
            echo "[$(date -u)] Error: Failed to log in to Docker Hub"
            exit 1
          fi

      - name: Tag Docker image
        run: |
          echo "[$(date -u)] Tagging Docker image..."
          docker tag kikibuh/frontend:latest "${{ secrets.DOCKERHUB_USERNAME }}/frontend:latest"
          if [ $? -eq 0 ]; then
            echo "[$(date -u)] Tagged Docker image successfully"
          else
            echo "[$(date -u)] Error: Failed to tag Docker image"
            exit 1
          fi

      - name: Push Docker image
        run: |
          echo "[$(date -u)] Pushing Docker image..."
          docker push "${{ secrets.DOCKERHUB_USERNAME }}/frontend:latest"
          if [ $? -eq 0 ]; then
            echo "[$(date -u)] Pushed Docker image successfully"
          else
            echo "[$(date -u)] Error: Failed to push Docker image"
            exit 1
          fi

      - name: Task complete
        run: echo "[$(date -u)] Task complete"

        ##
