name: Build and Push Docker Image to Dockerhub

on:
  push:
    branches:
      - pipeline

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        run: docker buildx create --use

      - name: Build Docker image
        run: |
          echo "[$(date -u)] Building Docker image..."
          docker buildx build --platform linux/amd64,linux/arm64 -t frontendimage:latest -f docker/Dockerfile .
          if [ $? -eq 0 ]; then
            echo "[$(date -u)] Built Docker image successfully"
          else
            echo "[$(date -u)] Error: Failed to build Docker image"
            exit 1
          fi

      - name: Login to Docker Hub
        run: |
          echo "[$(date -u)] Logging in to Docker Hub..."
          echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
          if [ $? -eq 0 ]; then
            echo "[$(date -u)] Logged in to Docker Hub successfully"
          else
            echo "[$(date -u)] Error: Failed to log in to Docker Hub"
            exit 1
          fi

      - name: Tag Docker image
        run: |
          echo "[$(date -u)] Tagging Docker image..."
          docker tag kikibuh/frontendimage:latest "${{ secrets.DOCKERHUB_USERNAME }}/frontend-image:latest"
          if [ $? -eq 0 ]; then
            echo "[$(date -u)] Tagged Docker image successfully"
          else
            echo "[$(date -u)] Error: Failed to tag Docker image"
            exit 1
          fi

      - name: Push Docker image
        run: |
          echo "[$(date -u)] Pushing Docker image..."
          docker push "${{ secrets.DOCKERHUB_USERNAME }}/frontend-image:latest"
          if [ $? -eq 0 ]; then
            echo "[$(date -u)] Pushed Docker image successfully"
          else
            echo "[$(date -u)] Error: Failed to push Docker image"
            exit 1
          fi

      - name: Task complete
        run: echo "[$(date -u)] Task complete"
